spring.application.name=inventory-management
server.port=8080

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_db
useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=postgres
spring.datasource.password=2019@Ritik
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# OpenAPI / Swagger UI Path
springdoc.swagger-ui.path=/swagger-ui.html